spring.application.name=Cashfy-api

# Server
server.port=8081

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Logging Configuration
logging.level.com.example.Cashfy_api.auth=DEBUG
logging.level.org.springframework.security=DEBUG